spring:
  security:
    user:
      user: admin
      password: admin123
  profiles:
    active: dev
  main:
    allow-circular-references: true

  datasource:
    url: 'jdbc:h2:~/tistechdb'
    driverClassName: org.h2.Driver
    username: sa
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true

logging:
  level:
    com: INFO
    br: DEBUG
    org.springframework: INFO
